\title{Extenstion for rectilinear grids with non-overlapping grids lines}


## Kernels / covariance matrices

\begin{aligned}
\quad k\left(A_{H}, A_{H}\right) := k\left(X^*, X^*\right) : \text{ base covariance, }\\
\quad k\left(A_{H}, A_{L}\right) := k\left(X^*, X \right) \\
\quad k\left(A_{L}, A_{L}\right) := k\left(X, X \right)\\
\end{aligned}

## Differentiate between target grid and auxiliary grid
Area-weighted interpolation (also referred to as mimetic interpolation)

\begin{aligned}
\quad k\left(A_{H_{aux}}, A_{H_{aux}}\right) \\
\quad k\left(A_{H_{target}}, A_{H_{target}}\right) := k\left(X^*, X^*\right) : \text{ base covariance, }\\
\quad k\left(A_{H_{target}}, A_{L_{target}}\right) := k\left(X^*, X \right) \\
\quad k\left(A_{L_{target}}, A_{L_{target}}\right) := k\left(X, X \right)\\
\end{aligned}


## Predictive mean and covariance
\begin{aligned}
\quad \mu^{*} = P^{*}\left(A_{H}\right)= k\left(A_{H}, A_{L}\right)\left[k\left(A_{L}, A_{L}\right)+\sigma_{n}^{2} \mathbf{I}\right]^{-1}\left(P_{L}\left(A_{L}\right)-\mu\right) + \mu \\
\quad \mu^{*} = P^{*}\left(A_{H_{target}}\right)= k\left(A_{H_{target}}, A_{L_{target}}\right)\left[k\left(A_{L_{target}}, A_{L_{target}}\right)+\sigma_{n}^{2} \mathbf{I}\right]^{-1}\left(P_{L}\left(A_{L_{target}}\right)-\mu\right) + \mu \\
\quad \Sigma^{*} = k\left(A_{H}, A_{H}\right)-k\left(A_{H}, A_{L}\right) \left[k\left(A_{L}, A_{L}\right)+\sigma_{n}^{2} \mathbf{I}\right]^{-1}k\left(A_{L}, A_{H}\right)\\
\quad \Sigma^{*} = k\left(A_{H_{target}}, A_{H_{target}}\right)-k\left(A_{H_{target}}, A_{L_{target}}\right) \left[k\left(A_{L_{target}}, A_{L_{target}}\right)+\sigma_{n}^{2} \mathbf{I}\right]^{-1}k\left(A_{L_{target}}, A_{H_{target}}\right)
\end{aligned}

# Log Marginal liklihood
\begin{aligned}
\quad log\left(p\left(\mathbf{y} \mid \mathbf{X}, \theta \right) \right) =-\frac{1}{2} \mathbf{y}^{T} \, K_{X}^{-1} \, \mathbf{y}-\frac{1}{2} \log \left|K_{X}\right|-\frac{N}{2} \log 2 \pi\\
\quad log\left(p\left(\mathbf{y} \mid \mathbf{X}, \theta \right) \right) =-\frac{1}{2} \mathbf{y}^{T} \, \left[k\left(A_{L}, A_{L}\right)+\sigma_{n}^{2} \mathbf{I}\right]^{-1} \, \mathbf{y}-\frac{1}{2} \log \left|\left[k\left(A_{L}, A_{L}\right)+\sigma_{n}^{2} \mathbf{I}\right]\right|-\frac{N}{2} \log 2 \pi\\
\end{aligned}